### ISSUE TITLE
SketchApp Symbols

### ISSUE THREAD

**Issue by iammichaelneal** [react-bootstrap-table/react-bootstrap-table2#1]
Would anyone be interested in a SketchApp file of visual design assets to accompany the react-bootstrap-table2 examples?

**Comment by AllenFang** [comment]
@iammichaelneal you mean like https://www.sketchapp.com/learn/documentation/symbols/ ?

**Comment by iammichaelneal** [comment]
@AllenFang correct.

**Comment by AllenFang** [comment]
got it.. I think it will be hard to implement in current lol. In my opinion, I wanna have a clean and easy way to find some real case or basic usage by example page, I think it will me more useful for most users, because in `react-bootstrap-table1`, a lots of user ask me some real case or some basic questions, I think it's not easy to find/navigate in my examples, so that's the problems I wanna fix.

Anyway, thanks your feedback and maybe you can have a PR in future to implement this awesome idea, thanks 👍
