### ISSUE TITLE
After New Release (2019-06-25), sizeperpage dropdown is not not opening

### ISSUE THREAD

**Issue by rashisinha** [react-bootstrap-table/react-bootstrap-table2#1003]
Hi @AllenFang 
After the latest release New Release (2019-06-25) , the sizeperpage dropdown is not working. When I click on it, it opens for the first time and subsequently nothing happens on further clicks. Using keyboard up and down keys, however, the dropdown opens and the "show" class is assigned correctly to display the dropdown. But further mouse clicks are not working.
Following is the package.json
    "react-bootstrap": "^0.32.3",
    "react-bootstrap-table-next": "^2.0.1",
    "react-bootstrap-table2-filter": "^1.1.1",
    "react-bootstrap-table2-paginator": "^2.0.6",

**Comment by AllenFang** [comment]
@rashisinha I can't reproduce this issue, [online example](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Basic%20Pagination%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is work. 

Please give me an example on codesandbox so that I can reproduce this defect, thanks
