### ISSUE TITLE
CellEditor Drowpdown give GetOptions() access to row and column props

### ISSUE THREAD

**Issue by mescoff** [react-bootstrap-table/react-bootstrap-table2#1027]
Hi,
I need my getOptions to have access to the Row information so that the dropdown shows options that are only relevant to my object row. Is it possible or does it need an inhancement? (In the meantime I had to create a custom EditorRenderer that takes the row and returns a drop-down with options created based on the row info)

Thanks!

**Comment by AllenFang** [comment]
@mescoff i will implement it soon, thanks

**Comment by bcobra** [comment]
I also need row and column information in getOptions. I tried using onStartEdit to get the data but then i couldn't wait asynchronously to get the values in getOptions

**Comment by AllenFang** [comment]
I fixed in newest version, please upgrade to newest version, thanks
[here](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/08/10/version-bump.html) is release note

[doc](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-celledit.html#editorgetoptions)

**Comment by bcobra** [comment]
Thanks!!
