### ISSUE TITLE
Toggling column empties current filter

### ISSUE THREAD

**Issue by jendamozna** [react-bootstrap-table/react-bootstrap-table2#1030]
Filter input field in table header is empty after column visibility is toggled.

1. enter filter
2. hide column - data are still filtered 
3. show column - data are still filtered 
4. filter is empty - data are still filtered

See example:

https://codesandbox.io/s/fragrant-framework-k8q99

**Comment by AllenFang** [comment]
@jendamozna yes, I think so far `react-bootstrap-table2` will not render hide column and didn't memorize the previous state as well, cause this bug. I will spend some time to see how to fix it.

btw, do you have any expected behavior about this problem?  I can just clean the column filter which is not present. But not everyone agree this solution I guess.

**Comment by jendamozna** [comment]
Hello, thanks. I expect it will behave the same way as e.g. in googlesheets/libreoffice/msexcel: after the column is toggled back, the filter will be visible in the filter input field.

Cleaning onHide/onShow doesnt seem to be handy..

**Comment by AllenFang** [comment]
> I expect it will behave the same way as e.g. in googlesheets/libreoffice/msexcel: after the column is toggled back, the filter will be visible in the filter input field.

it make sense, but this will take some time to implement cause of we don't memorize the filter's state when itself column being hidden.

**Comment by AllenFang** [comment]
@jendamozna I fixed in newest version, please upgrade to newest version, thanks
[here](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/08/10/version-bump.html) is release note

**Comment by jendamozna** [comment]
its working, thanks
