### ISSUE TITLE
column.editorRenderer: OnStartEdit not called

### ISSUE THREAD

**Issue by Devkutt** [react-bootstrap-table/react-bootstrap-table2#1039]
**Describe the bug**
When you click on a cell to edit it and it has a custom editor (column.editorRenderer), the onStartEdit-method is not called.
Although it is not described explititit in the documentation, I thought it would behave like a normal editor and the onStartEdit method would be called.
The onSaveCell method is called btw.

**To Reproduce**
1. Add a custom component via editorRenderer to a column
2. Add a onStartEdit method to the cellEditFactory
3. Click a cell within the column => the onStartEdit method is not called

**codesandbox**
[Sandbox](https://codesandbox.io/s/suspicious-dawn-tpbvu)

**Comment by AllenFang** [comment]
@Devkutt it's expected behavior for me, but it could be discussed when there're another developer have same concerns.  So far `onStartEdit` is being called in the "Editor" itself component, so if you custom the editor component via `column.editorRenderer`, `react-bootstrap-table2` can not call this event. 

As I said, if there're many people have same concern, then I will consider to improve this behavior. thanks

**Comment by BrentWillems** [comment]
I'm facing the same problem, I'm using the onStartEdit to calculate the next cell for my custom tabbing behaviour (btw is there any update from this issue: [207](https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/207) because if this would be fixed I would need to use the onStartEdit).
But is there a way to trigger the onStartEdit in a custom editorRenderer? (with the same params so I still have my indexes for row and columns)

**Comment by marcRobertHabib** [comment]
This is also an issue for me.

Because I  build a component around react-bootstrap-table2,  which save the current row when moving to another one.  I check that was moved to another row in onStartEdit.  When using a custom editor onStartEdit is not activated.

This is this part of the code:
    function onStartEdit(rec: TRec, col: BsColumn<TRec>, rowI: number, colI: number) {
        // Save previous records if moved to another row.
        if (rec !== curRecRef.current) {
            if (curRecNeedSave()) saveCurRec();
            curRecRef.current = rec;
        }
    }
