### ISSUE TITLE
Since column.type was added, complex data is saved as string

### ISSUE THREAD

**Issue by RudPer** [react-bootstrap-table/react-bootstrap-table2#1044]
Hello. Since somewhat recent update which implemented column.type broke saving of more complex data structures (like arrays or objects). As written in docs, column.type supports only string, number, bool and date.

If you do not set type, it is undefined which passes the first if (!type) in typeConvert and is automatically converted to string.

As a quick-fix you can define type as any random string so it saves it as it is, but it will show a error in console, warning that wrong type is supplied to column.

#1004 is related to this.

**Comment by AllenFang** [comment]
@RudPer please follow the instructions when you open an issue so that I can help you. 

I think for me the most important thing is put your code in codesandbox and keep it simple and minimal.

According your descriptions, Im still unclear about below parts:

1. why you add column.type for a complex data type?  any reason?
2. Even you don't use column.type, if your column type is array or object, how you made it editable?

I will reopen this issue when I got the clear code or explanation

AGAIN, PLEASE FOLLOW THE INSTRUCTION OF OPENING ISSUE, THANKS

**Comment by RudPer** [comment]
Hello, sorry for not being clear.

Here is codesandbox link - https://codesandbox.io/s/react-bootstrap-table-next-basic-example-tsrqc?fontsize=14

For example, this is customer table. Customers can have multiple phones, so having them in array is the best solution. But now when trying to save array, it will be transformed into string and will break everything, as cell formatter expects there to be array which can be joined together in a string.
To break it, try changing customer phone field.

And to answer your questions:
1) No, I would not add column.type for complex data type, but currently it automatically is transformed into string by typeConvert function.
2) By using editorRenderer and using something like that i have in codesandbox or multi select

I hope I'm more specific now.

**Comment by AllenFang** [comment]
@RudPer thanks your explanation. For the unsupport data type, I will not do any type change to avoid this issue, thanks!

**Comment by AllenFang** [comment]
@RudPer I fixed in newest version, please upgrade to newest version, thanks
[here](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/08/10/version-bump.html) is release note
