### ISSUE TITLE
Support making expansion depend on which column of a row was clicked

### ISSUE THREAD

**Issue by mhvelplund** [react-bootstrap-table/react-bootstrap-table2#1068]
**Question**
Is it possible to make expandRow include the column that was selected?

I have a `BootstrapTable` where I want to be able to show a different expansion, depending on which column thew user clicked. I can see which column was clicked by looking at the event in the `expandRow.onExpand` handler, but I haven't found a good way make the result of the subsequent `expandRow.render` call depend on it. 

I would like a column index as a parameter to the render method, and I would like a way to prevent expansion be returning false from the render method, e.g. not all columns need to cause an expansion of the row.

**Comment by AllenFang** [comment]
hello @mhvelplund sorry for lately reply. so far we only allow user to example row via "clicking on row" or "clicking on expand indicator". 

> I would like a column index as a parameter to the render method, and I would like a way to prevent expansion be returning false from the render method, e.g. not all columns need to cause an expansion of the row.

For your request, I think it's not that simple to do it in current design. because so far our row selection and expansion is based on row level instead of cell level.

In my opinion, there's a workaround but not sure if you can accept it or not lol

```
class RowExpandManagment extends React.Component {
  constructor(props) {
    super(props);
    this.state = { expanded: [] };
  }

  handleOnExpand = (row, rowIndex) => {
    const isExpanded = typeof this.state.expanded.find(x => x === row.id) !== 'undefined';
    if (!isExpanded) {
      this.setState(() => ({
        expanded: [...this.state.expanded, row.id]
      }));
    } else {
      this.setState(() => ({
        expanded: this.state.expanded.filter(x => x !== row.id)
      }));
    }
  }

  render() {
    const columns = [{
      dataField: 'id',
      text: 'Product ID'
    }, {
      dataField: 'name',
      text: 'Product Name',
      events: {
        onClick: (e, column, columnIndex, row, rowIndex) => this.handleOnExpand(row, rowIndex)
      }
    }, {
      dataField: 'price',
      text: 'Product Price'
    }];
    const expandRow = {
      renderer: row => (
        <div>
          <p>{ `This Expand row is belong to rowKey ${row.id}` }</p>
          <p>You can render anything here, also you can add additional data on every row object</p>
          <p>expandRow.renderer callback will pass the origin row object to you</p>
        </div>
      ),
      expanded: this.state.expanded,
      onExpand: () => this.forceUpdate()  // !!! important, avoid react-bootstrap-table render table with new internal expand states.  
    };
    return (
      <div>
        <button className="btn btn-success" onClick={ this.handleBtnClick }>Expand/Collapse 3rd row</button>
        <BootstrapTable keyField="id" data={ products } columns={ columns } expandRow={ expandRow } />
        <Code>{ sourceCode }</Code>
      </div>
    );
  }
}
```


The idea is
1. Add `column.events.onClick` on the column which you want to trigger expand event only
2. In the callback of `column.events.onClick`, you can manage expand states by yourself.
3. Avoid `react-bootstrap-table` re-render the table with internal expand states via `forceUpdate`

Do let me know if you have any question, thanks

**Comment by mhvelplund** [comment]
Thanks! I'll have a look at it Monday when I get back to work ;)

**Comment by Bopzor** [comment]
Hello !
Thank you for this workaround.

I try it and it work. But I have `editable: true` set on one column (`mode: 'click', blurToSave: true`) that do not work any more. I find out that the `forceUpdate` seems to block the edit because when I remove this part, edit work (but row expand on any column click).
Is there a way to trigger Editing ? In that way I could render my custom editor on column click event by myself.

Thank you, I love working with `React-bootstrap-table2 :)

**Comment by AllenFang** [comment]
hello, @Bopzor 

i think your case is because you try to set state for manage the row expand, however, it break the call of cell editing. But I think there's still a workaround is trigger cell editing via expose api: 

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/exposed-api.html#trigger-cell-editing

**Comment by donnrri** [comment]
I solved this using
```
              events: {
                onClick:  e => e.stopPropagation()
              }
```

On each column I wanted to NOT expand the row when clicked on , leaving the one I DID want the click to expand the row without that code.
