### ISSUE TITLE
Search the table with "StartsWith" instead of "Contains"

### ISSUE THREAD

**Issue by webwasim** [react-bootstrap-table/react-bootstrap-table2#1078]
I have a very basic requirement to search the table columns using the StartWith instead of the default "Contains" method.
Any Help would be grateful.

**Comment by jendamozna** [comment]
did you try onFilter?
https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Implement%20custom%20filter%20logic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by webwasim** [comment]
But this example filter the individual column. I want a one search field like a table search.

**Comment by AllenFang** [comment]
@webwasim so far we don't have this feature, but I think I can implement it, thanks!

**Comment by webwasim** [comment]
Ahh,, Can you tell me what search hook i can use to implement this feature ? what method do you call when we search?

**Comment by AllenFang** [comment]
@webwasim in my fixes, I give you a hook to perform the custom match.  Will release this patch soon

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/09/08/version-bump.html)

This issue was fixed, please upgrade all the packages listed in above 

Now, you have to custom your search logic via [`search.onColumnMatch`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/search-props.html#searchoncolumnmatch-function)

[online demo](react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Table%20Search&selectedStory=Custom%20match%20function&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panelonsumer.app.com.tw:8888)
