### ISSUE TITLE
FOOTER: how to know another cells in current row for footer

### ISSUE THREAD

**Issue by Menogus** [react-bootstrap-table/react-bootstrap-table2#1081]
**Question**
in footer i need sum of multiplication two cells.
how to know data of another cells?

need something like:

```
footer: (column, cell, index,  ROW) => {
 ..... console.warn(ROW.cell1, ROW.cell2)
}
```

**Comment by maxsilvauk** [comment]
Yes we need access of column, cell, index and row in footerEvents(

**Comment by AllenFang** [comment]
@Menogus actually, we already pass `column` object and `columnIndex` as second and third arguments of `footer` function.  But i didn't mentions footer usage in docs, I will enhance docs ASAP, thanks

following is the source code:
https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/packages/react-bootstrap-table2/src/footer-cell.js#L31

Anyway, I can pass the `row` because it's impossible!

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/09/08/version-bump.html)

I update the [docs](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnfooter-string-function)
