### ISSUE TITLE
[Feature] Define wich columns can expand

### ISSUE THREAD

**Issue by Michael-sub** [react-bootstrap-table/react-bootstrap-table2#1112]
Hello,
In the previous version of the table there was the possibility to choose the mode in which you wanted to expand the table: by row or by column.
[Link to the doc](http://allenfang.github.io/react-bootstrap-table/docs.html#expandBy)

Now we can' t choose which columns do the expand of the table, leading to unwanted behaviour  in some cases (e.g. Dummy columns with buttons where clicking the button expands the row in addition to executing its action)

Would be great if we could define wich columns allow the expand of the row

**Comment by AllenFang** [comment]
Hello, sorry for lately reply and so far I'm not going to implement expand by column feature, because it will lead complex in source code and make few wired bug when combine with row selection. It's the experience in legacy `react-bootstrap-table` I learned and actually, there're no much developer need this feature so far. 

Let's close it but if many people ask for this feature, I will consider it again, thanks =)
