### ISSUE TITLE
Prop `row` is undefined in Cell when searching from 2nd page using Toolkit & Pagination.

### ISSUE THREAD

**Issue by brohera** [react-bootstrap-table/react-bootstrap-table2#1118]
@AllenFang 

I can reproduce the bug #495 & #839  in the latest version:
react-bootstrap-table-next@3.2.1
react-bootstrap-table2-toolkit@2.1.0
react-bootstrap-table2-paginator@2.1.0

In addition, I have a related issue.
To reproduce:

1. Create a table that has at least 2 pages.
2. Search for something on the 2nd page which returns some result.

This will give a warning in the console that prop `row` is required in Cell but its value is undefined. If you use a formatter for any cell the app will crash as the parameter row passed in formatter function is undefined.

I would really appreciate your help with this. And thank you for this library.

I have created a demo on codesandbox.io for your reference. You can check it [here](https://codesandbox.io/embed/react-bootstrap-table-next-basic-example-e8jbl)

**Comment by eyle** [comment]
Hello,

I confirm this bug , it's really disgusting as an issue since when using formatter to format Data in table , this causes page to crash , you have to type slowly in order to avoid this problem or avoid formatter :( .

Good Luck fixing it and thx for this amazing DataTable 👍  .

**Comment by AllenFang** [comment]
Sorry for lately reply, i will check this out, thanks you guy's support !!

**Comment by AllenFang** [comment]
@eyle  @brohera You have to render `PaginationProvider` as child of `ToolkitProvider`  then you will fix this issue:

```js
<ToolkitProvider>
  {() => {
    <PaginationProvider>
    { .... }
    </PaginationProvider>
  }}
</ToolkitProvider>
```


sorry about this issue, I will mention this tricky part in official docs.

Let me know if you guys still have questions, thanks

**Comment by npomfret** [comment]
Can't figure this out.  The row param is always undefined in my formatter function

**Comment by charliemoriarty** [comment]
@AllenFang Thanks for all the work you do on this project! 

We've been having some trouble with this crash as well, which happens when we use both a `ToolkitProvider` and `PaginationProvider` and try searching for items when on the the second+ page of results. It also occurs if we update the `data` value to a new array size that's smaller than the previous array, whilst we're on a page of results that's expecting the larger value.

Unfortunately reversing the order of the providers didn't fix the issue - but we've been able to solve this by reverting to the `BootstrapTable` default paginationFactory and not using the custom `PaginationProvider`. Do you know if there's any way to use the custom provider without encountering this crash?

**Comment by wjazzar** [comment]
Hello, 

I actually resolved this issue by checking if the row is undefined , if it's true , i return empty String depending on type.
But What really happen , it get's reupdated again  and React  update the view with the row containing the data, you won't even notice the difference at all.

I suggest you to check for Row variable as well as other variable if you need them , and return empty data , The row will get updated just after that and your data will always be present(Without even noticing it).

That's the only way i could prevent this issue.

Hope i did help you. 

Please Note that i used this format :
```
<ToolkitProvider>
  {() => {
    <PaginationProvider>
    { .... }
    </PaginationProvider>
  }}
</ToolkitProvider>
```

**Comment by hauhuynh1208** [comment]
@eyle I am facing the same issue. Could you please post a gist of your solution?
