### ISSUE TITLE
column.sortValue not working in remote mode

### ISSUE THREAD

**Issue by martinsura** [react-bootstrap-table/react-bootstrap-table2#1121]
**Describe the bug**
Hello,  i need change default sort value send to the server(backend).
I try:
`  column.sortValue { dataField: "id", title: "Id",sortValue:() => "customId"  } `, 

After sort is init, client send "id" instead "customId" as sort property.
Is there any workaround, how to change sortProperty in remote mode?

Thanks

**Comment by AllenFang** [comment]
@martinsura when you using the remote mode, which mean you have to handle the logic of sorting.  `sortValue` is only work in non-remote mode because sorting is occur in table internally.

BTW, the sortValue is not mean the `dataField`, it means the actual value when sorting happing

for ex:

your data is

```js
[{ .id: 'a' }, { id: 'b' }]
```

When sorting on `id` field, you can change the actual sort value via `sortValue` and transfer it as like 

[{ .id: 'a1' }, { id: 'b1' }]
