### ISSUE TITLE
csv / search configurations

### ISSUE THREAD

**Issue by nirkrumer** [react-bootstrap-table/react-bootstrap-table2#1158]
Hey,
Can you explain me what do I need to configure under { ...props.csvProps }
,or in:  <SearchBar { ...props.searchProps } /> and so on

![image](https://user-images.githubusercontent.com/38032506/68587096-e6119300-048e-11ea-8c78-500df013635d.png).

Can you show me an example? I don't understand which values I need to put

Thanks,
Nir

**Comment by AllenFang** [comment]
@nirkrumer you have to pass `csvProps` to exportcsv button and same way for bootstraptable component.

in you screenshot, it's necessary action that you have to do. the reason is `ToolkitProvider` is a context which allow developer easy to customize the component like export csv button, search input etc. 

So in most simple case (without customization), you can just ignore the contents of these props(`csvProps`, `searchProps`) and pass them to corresponding component.

**Comment by nirkrumer** [comment]
I'm trying to understand what is missing.
i see the button but it doesnot do nothing

![image](https://user-images.githubusercontent.com/38032506/68876992-026f3300-070e-11ea-903a-73b57885daac.png)
