### ISSUE TITLE
react-test-renderer errors on filters

### ISSUE THREAD

**Issue by QuarterSprout** [react-bootstrap-table/react-bootstrap-table2#1187]
**Question**
I have successfully implemented react-bootstrap-table2 in my code and it works fine to use it. I am not able to write tests for any table that has react-bootstrap-table2-filters, though.

**codesandbox**
The stack trace is very long but the important part is that every filter gives me this error in their respective componentDidMount function:  Error: Uncaught [TypeError: Cannot read property 'value' of null]

I get the same error for numberFilter, textFilter, dateFilter

My table code:

const columns = [
  {dataField: 'amount', text: 'Amount', sort: true, filter: numberFilter()},
  {dataField: 'when', text: 'Date', sort: true, filter: dateFilter(), formatter: dateDisplay},
];

const TransactionsTable = (props) => (
  <BootstrapTable bootstrap4 hover condensed 
                  filterPosition='top' 
                  keyField='when' 
                  data={props.transactions || []} 
                  columns={columns} 
                  filter={ filterFactory() }
                  pagination={ paginationFactory({sizePerPage:50}) } />
)

My test looks like this: 
  it('Renders the table', async () => {
    let component;
    await renderer.act(async () => {
      component = renderer.create(
        <TransactionsTable transactions={transactions} />
      );
    });
    const tree = component.toJSON()
    expect(tree).toMatchSnapshot()
  })

**Comment by AllenFang** [comment]
hello @QuarterSprout sorry for lately reply, I can't read your code, would you please refine it? thanks. btw, I usually don't have too much time on this project, if you can please give a minimal and simple example on codesandbox so that I can quickly figure out the root cause. thanks

I will reopen this issue until I have a codesandbox and a readable code.

**Comment by QuarterSprout** [comment]
Here it is in a sandbox, though I am getting a different error there that seems specific to codesandbox. 

https://codesandbox.io/s/boring-river-e3w7v

**Comment by AllenFang** [comment]
@QuarterSprout I guess this is not related to `react-bootstrap-table`, I can't pass the test even I gave a very simple table component or just a `<div>` based on your code. I think you have to figure out this issue by `react-test-renderer `, I'm not familiar to this testing library so sorry about I can't help u. thanks

**Comment by batcer** [comment]
I have exactly the same problem, and my test runs smoothly with empty `<div/>`, but throws this exception when TestRenderer is given a component containing react-bootstrap-table-next with a filter.

It seems that @AllenFang hadn't understood the problem: it's not that the test isn't passing, it's that it raises an exception while running, so it can't neither pass nor fail, it just doesn't work with RBT. 

And the reason is that RBT relies on `refs`. To fix the exception, you have to provide a function for mocking ref to `renderer.create`: 
```
const testRenderer = TestRenderer.create(
      <YourComponentWithTable/>,
      {createNodeMock: (element) => ({})}
  );
```
That fixed tests for me.
