### ISSUE TITLE
The row with the filters doesn't inherit column/columnHeader classes

### ISSUE THREAD

**Issue by osnofa** [react-bootstrap-table/react-bootstrap-table2#1208]
**Describe the bug**
When adding the filterPosition="top" property to the table, not only does the row with the filters not inherit the classes defined in column.headerClasses, I also couldn't find any way to define its own classes in the documentation.

**To Reproduce**
1. Create filters for the columns
2. Also add classes to the columns and headers, for instance, the following bootstrap classes:
`  const columns = [{ ... headerClasses: "col-2", classes: "col-2", filter: ... )} ... ],`
and
`<BoostrapTable ... headerClasses="thead-light d-flex" rowClasses="d-flex" filterPosition="top" />`
3. Add filterPosition="top" property to the table
4. The table isn't displayed correctly (because the row with the filters doesn't have the css classes)

**Screenshots**
The first table without classes and the second with bootstrap classes:
![Screenshot_2019-12-20 cocky-bash-wth5m - CodeSandbox](https://user-images.githubusercontent.com/24547517/71269272-d6ffe980-2346-11ea-9dae-649f0704981b.png)

**codesandbox**
https://codesandbox.io/s/cocky-bash-wth5m

**Comment by AllenFang** [comment]
@osnofa sorry for lately reply, that is because the top filter is render by another `tbody`, and for example if you add `striped` that will cause this issue. So I think on my end I will not fix this issue but there's a workaround is you can disable bootstrap striped css on first `tbody` and `tr` when you use top filter.
