### ISSUE TITLE
OnClick event row object not updating edit field in the table

### ISSUE THREAD

**Issue by kennethliang** [react-bootstrap-table/react-bootstrap-table2#1230]
OnClick event row object not updating edit field in the table.

If a have a column of an edit field. Let's call it "enter_bid" field.
{
        dataField: "enter_bid",
        text: "Enter Bid",
        editable: true,

}

and then a have a button used for submitting the value to the server.
    {
        dataField: "bid_button",
        text: "Bid",
        editable: false,
        formatter:   (cell, row, rowIndex, extraData) => (  <div>
            <button type="button" className="btn btn-primary"  >
                Bid
            </button>
        </div>),
        events: {
            onClick: (e, column, columnIndex, row, rowIndex) => {
alert(row.enter_bid);
}

The row.enter_bid object sometime anomaly returning a null value even if there's a value in the edit field
It seems the row object in the onClick function it's not updating.

**Comment by thebradisrad** [comment]
Maybe because the table hasn't had time to load your data that is fetched asynchronously. Try to store your selected value in a state. 

this.state = {
enterBid: ''
}
this.onClickBid = this.onClickBid.bind(this);

onClickBid(enterBid) 
{
this.setState({enterBid);
alert(this.state.enterBid);
}

{
dataField: "bid_button",
text: "Bid",
formatter: (cell, row) => {
return (<span><button onClick={()=>this.onClickBid(row.enter_bid)}>Show Bid</button></span>
}
}

**Comment by AllenFang** [comment]
@kennethliang your code seems unreadable. please update.
