### ISSUE TITLE
Changing attribute values afterwards

### ISSUE THREAD

**Issue by Nervanas** [react-bootstrap-table/react-bootstrap-table2#1263]
Hello,

I created a table where I need to modify data (especially content and styling) of specific cells, _after_ creation (during runtime).

Are there any implementeds methods on doing so - currently im struggling?

Thanks for your help.

Edit: To be more specific: I have checkboxes as values and after pressing a button (like submit or something like that) I want to change the cells i.e. where the checkbox is checked.

**Comment by AllenFang** [comment]
about cell content, we have [`column.formatter`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function), you can use it to customze the cell content 

about cell styling, classname etc, you can use [`column.style`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnstyle-object-function) or `[column.classes](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnclasses-string-function`)

About your requirement, when something trigger, you definitely know which row and cell you have to custome by save these data in the state, then you can use above props to do anything you want.

Please read docs and discover [online demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html) if you get question in the beginning.

Please open another issue if you still have any question, close it due to no further action.
