### ISSUE TITLE
Can we change the formatter to async function?

### ISSUE THREAD

**Issue by adamcanray** [react-bootstrap-table/react-bootstrap-table2#1311]
**Question**
Can we change the formatter to async function?

**Description**
I have a REST API that returns an image when I request with the url + (plus) file name and I want to display it in the image column in a table.
[My Question on stackoverflow](https://stackoverflow.com/questions/60944886/how-do-i-display-base64-inside-map-loopassumption-in-reactjs/60986338?noredirect=1#comment107896675_60986338)

**codesandbox**
https://codesandbox.io/embed/nifty-sinoussi-l08kk?fontsize=14&hidenavigation=1&theme=dark

**Error**
> Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.

**Comment by adamcanray** [comment]
I ask above because I have a case that asks I use await from the async function. I want to retrieve a **Base64** decoded string for me to display as an image with the ```<img src = {Base64String} />``` tag in a column in the table. <br>
I have tried to use the async function in the formatter and it cannot, it always get an error like this: <br>

> Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.

but I still get **Base64 string** that I want in the **console** and I began to think that it is not possible to place the async function in the formatter. I have tried to apply the formatExtraData, but in my opinion it does not suit my case. is there any alternative? if there is i will be very thankful ..

@AllenFang

**Comment by AllenFang** [comment]
HI @adamcanray I'm sorry I will not consider to implement this feature. For you case, you have to implement a custom component to display an image, like ImageURI component and render it when calling the `formatter`.  So in this custom component, you can do anything you like, for example: fetching the data and only render `<img />` element when data is availabe.

That's why I reject your requirement. because this is all are able to control by you. 

Please open another issue if you still have any question or any issues, thanks boss
