### ISSUE TITLE
Default sorted column does not show caret hilites

### ISSUE THREAD

**Issue by reposman33** [react-bootstrap-table/react-bootstrap-table2#1321]
Hello,
as the subject says..... I have a table, I sort it by 1 of the columns through the table.defaultSorted prop:
```
		this.table = {
			defaultSorted: [
				{
					dataField: "dateTimeCreated",
					order: "asc",
				},
			],
			defaultSortDirection: "desc",
```
The data is sorted by the column and I see the 2 up-down carets but I none of them is highlighted. I expected 1 of them to be highlighted so it reflects the sort column and sort direction.
Currently none of the sortable columns have their carets highlighted.

Do I need to add some other prop?

**Comment by AllenFang** [comment]
Maybe there're some styles got override
The online example for bootstrap3 and 4 are work well
https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Sort%20Table&selectedStory=Default%20Sort%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Bootstrap%204&selectedStory=Sort%20table%20with%20bootstrap%204&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Please open another issue when you have enough information so that I can help u...

**Comment by EddyIonescu** [comment]
In case anyone else runs into this, adding `bootstrap4` (as in the second link) resolved this for me.
