### ISSUE TITLE
Get Expanded row data

### ISSUE THREAD

**Issue by aZolo77** [react-bootstrap-table/react-bootstrap-table2#1337]
may be was requested before..

This lib doesn't have responsive mode, so I had to make it myself by adding some classes and styles.
With the help of mediaScreen requests i hide some columns and show hidden collumns info in expanded row, but there is one issue: I don't have access to this row, until it appears and even in method onExpand. It has display: table-cell and it automaticcaly gets colspan that is equal to number of columns in the table (and some of them are "display: none" in my case).. So, cause i don't have access - i can't change this colspan value and cause of that width of this expanded row is bigger than width of all other rows.. So, can u give me any advice on how to fix all that?

I also tryed to change expanded row styles by giving it "dispay: block or flex" instead of table-cell, but it causes some freezes when it closes. 

I hope there will be Responsive mode someday, like in DataTables on pure JS

Thanks

**Comment by AllenFang** [comment]
I agree the responsive is an issue so far.  In term of your case, this case seems too complicated and I can't totally understand what you done so far. Would u please give me a small and simple code on codesandbox?, so that I can help u.

Anyway, your case sounds complicated, not sure if I can help u or not
