### ISSUE TITLE
Sort/Search the Select-Column to find rows that are selected

### ISSUE THREAD

**Issue by hmrc87** [react-bootstrap-table/react-bootstrap-table2#1379]
**Question**
Hi, I have a relativly large table where a user is able to select one or multiple rows from. Those come also preselected when the table is loading. Now I want tobe able to let the user sort/filter out those rows that are already selected or not selected.

I tried creating a dummy column and getting the information if the row is selected or not. Unfortunately the table does not react on the store changes (MobX) so that is currently not an option. 

Can we somehow filter/search the select/Checkbox column?

![image](https://user-images.githubusercontent.com/1226017/82296822-109a5680-99b2-11ea-889b-15b0e52fdde5.png)

**Comment by amitsetty** [comment]
I would just store the selection as part of the object outside the table and would filter the values I'm passing into react bootstrap table - something like this 

tableData={getFilteredData(tableData)}

function getFilteredData(tableData){
return tableData.filter(data=>data.selected)
}

**Comment by AllenFang** [comment]
@hmrc87 please give a simple and minimal code on codesandbox so that I can help u. 
BTW, please remember that don't mutate the props data, we use `shouldcomponentupdate` to avoid unnecessary rendering, I guess you mutate the data so that cause the cell didn't get rerender.  Toooo many issues reported here is related to mutation issue. So please be caution to it.

Please open another issue if the issue still remains, and remember to give your code...

thanks
