### ISSUE TITLE
nonSelectable not disabling selection

### ISSUE THREAD

**Issue by HZSamir** [react-bootstrap-table/react-bootstrap-table2#1547]
Hello,
Setting `nonSelectable` does not disable the selection of the rows specified. You can still check each checkbox.
I have reproduced a minimal example from the [docs](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Not%20Selectabled%20Rows%20Class&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).

**codesandbox**
https://codesandbox.io/s/nifty-stallman-py44w?file=/src/App.js

**Comment by Ymbere** [comment]
Hey @Unforgiven-wanda, thank you very much for providing the example!
It makes it a lot easier to analyze the problem, your code is pretty much right, there is just this one thing that you forgot.

The `nonSelectable` rows property takes an array of the key values that you want to be disabled.

Here is the object that you provided has data for the table.

```jsx
const products = [
  { id: "1", name: "name", price: 10 },
  { id: "2", name: "name", price: 20 },
  { id: "3", name: "name", price: 30 }
];
```
Since you specified in the table that the key is the `keyField="id"` 

```jsx
  <BootstrapTable
    wrapperClasses="table-responsive"
    keyField="id"
    data={products}
    columns={columns}
    selectRow={selectRow}
  />
```
You just have to match the values on the `nonSelectable` property, the id is a string, not an integer

```diff
-   nonSelectable: [0, 1, 2],
---
+   nonSelectable: ["0", "1", "2"],
```

Here is a working example

[![Edit recursing-noyce-0nvte](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recursing-noyce-0nvte?fontsize=14&hidenavigation=1&theme=dark)

**Comment by HZSamir** [comment]
Thank you for your time and the thorough explanation.
