### ISSUE TITLE
Filtered table doesn't rerender on prop change

### ISSUE THREAD

**Issue by gjakab** [react-bootstrap-table/react-bootstrap-table2#303]
So when the table is filtered and it's data prop is changed then the table won't rerender until you change the filter again. Is there any way to make it rerender? Or in my case an other option would be to reset the table filters but I didn't find a clear solution for that.

**Comment by AllenFang** [comment]
> So when the table is filtered and it's data prop is changed then the table won't rerender until you change the filter again

HI @gjakab could you please share more? code and flow.

> Or in my case an other option would be to reset the table filters but I didn't find a clear solution for that.

We will have a implementation for filter table pragmatically in next version, it can be a workaround for this requirement, anyway, we will implement the clean filter functionality. thanks

**Comment by tapioko** [comment]
Example flow:
1) Type something in the column filter
2) => At least one row is still visible
3) Somehow remove that row from original data or modify row's data so that row should disappear (because filter text does not match row data anymore)
4) => Row does not disappear
5) Add one character to the column filter and then remove the added character
6) => Table is updated and the row disappears

**Comment by AllenFang** [comment]
Hi @tapioko when you modify the raw data, did you sync the data to table again? I mean maybe render table by calling `setState`?

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/05/13/version-bump.html

Fixed on `react-bootstrap-table2-filter@0.1.7`
