### ISSUE TITLE
Cell OnClick Events

### ISSUE THREAD

**Issue by chaserda** [react-bootstrap-table/react-bootstrap-table2#427]
Is there a way to trigger an event by clicking a specific cell? 
I cant have it be a whole row selection. It needs to be a specific cell.

**Comment by AllenFang** [comment]
Hello @chaserda I think you can try [`column.events`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnevents-object). This will add event on whole specific column instead of cell, but you can filter out what cell you want to handle in the callback.

Do let me know and reopen this issue if above solution is not fit your requirement. thanks

**Comment by vasilevich** [comment]
how can I modify the state from the column event?  the "this" is not being transfered down to the event and there is no way to do so?

**Comment by bjostes** [comment]
@AllenFang how do I get the row id, when using column event for clicking on specific cell?
So when I click at a specific cell, I would like to know which Id the row has, the cell belongs to.

**Comment by KoGaYoung** [comment]
when i encountered this same problem today, i use cellEdit (https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/docs/cell-edit.md).  if you compare old value , new value, you can use this onChange.

**Comment by Jocatins** [comment]
> Is there a way to trigger an event by clicking a specific cell? I cant have it be a whole row selection. It needs to be a specific cell.
@chaserda did you later figure this out
