### ISSUE TITLE
CSV Export only current items

### ISSUE THREAD

**Issue by chaserda** [react-bootstrap-table/react-bootstrap-table2#464]
Is there a way to only export the items currently displayed on the table based on filters instead of exporting the whole list?

**Comment by AllenFang** [comment]
@chaserda fixed in `react-bootstrap-table-next@1.1.0` and `react-bootstrap-table2-toolkit@1.0.1`

Configure [`exportCSV.exportAll`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/export-csv-props.html#exportcsvexportall-bool) as `false` will achieve your requirement.

[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/08/12/version-bump.html)
