### ISSUE TITLE
`sortFunc`: expose row data to custom sort function

### ISSUE THREAD

**Issue by dovfriedman** [react-bootstrap-table/react-bootstrap-table2#501]
Have you thought about exposing the row data to the custom sort function instead of just the compare values, order and dataField? This would allow for more complicated sorting or is that why `remote sort` exists.

**Comment by AllenFang** [comment]
@dovfriedman ok, I will export the "row data" for both compare value. Will be implement in next release, thanks you

**Comment by AllenFang** [comment]
@dovfriedman fixed in `react-bootstrap-table-next@1.1.3`

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/08/27/version-bump.html
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnsortfunc-function

Please reopen this issue and tag me if the problem still remain in newest version. thanks

**Comment by dovfriedman** [comment]
Perfect. Thanks @AllenFang.
