### ISSUE TITLE
how can I prevent the default behavior of save?

### ISSUE THREAD

**Issue by Dmitri85** [react-bootstrap-table/react-bootstrap-table2#549]
Hi there

how can I prevent the default behavior of save (onBlur and enter)?
I just what to use the save hooks because I use MST and I cant modify values directly.
TNX

**Comment by AllenFang** [comment]
@Dmitri85 sorry I am not very clear about your question:



> how can I prevent the default behavior of save (onBlur and enter)?

You mean you don't want to use cell edit to update the value, right?



> I just what to use the save hooks

What kind of hook you need? would you please explain more?

**Comment by Dmitri85** [comment]
I just what to use beforeSaveCell method to call my mobx-state-tree action instead the default save(on blur or enter)

**Comment by AllenFang** [comment]
> I just what to use beforeSaveCell method to call my mobx-state-tree action

What kind of stuff you want to do in your mbox action?!

**Comment by Dmitri85** [comment]
I want to call action to set new value at the store clone

**Comment by AllenFang** [comment]
sorry, I can not figure out your problem. In addition, I still didn't understand what's means for "how can I prevent the default behavior of save (onBlur and enter)?"   Please clarify you question and provide some codes if you can, thank you.  

I wanna close this issue. Due to waste so many time.  Feel free to reopen it if you are ready to share you problem CLEARLY
