### ISSUE TITLE
Can we make an async validation ?

### ISSUE THREAD

**Issue by M3yo** [react-bootstrap-table/react-bootstrap-table2#604]
Hi,

I have an autocomplete/Dropdown editor in my table.

I would like to make an async call in my column validator, but I can't make it work because my call (axios) is async... and [validator ](https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/react-bootstrap-table2-paginator%401.0.3/packages/react-bootstrap-table2-editor/src/editing-cell.js#L86)doesn't seem to handle promises.

Is there any trick or something that I could do to get it work ?

**Comment by AllenFang** [comment]
@M3yo hmm... right now we don't support the async validation on cell editing, I will find some time to implement it.  thanks.  

I think right now the workaround is u have to enable `remote` mode for cell editing.  [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Remote&selectedStory=Remote%20Cell%20Editing&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an example you can learn.

Following is remote docs:
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-remote.html

I suggest to read it and decide if use remote mode. because it will be a big change when you enable pagination particularly


Feel free to let me know your question or ideas. thanks
Allen

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/10/29/version-bump.html)

[ONLINE DEMO](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Cell%20Editing&selectedStory=Async%20Validation&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

[DOCS](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnvalidator-function)

**Comment by M3yo** [comment]
Thanks a lot Allen !
