### ISSUE TITLE
Styling filters

### ISSUE THREAD

**Issue by vwen01** [react-bootstrap-table/react-bootstrap-table2#689]
![image](https://user-images.githubusercontent.com/19830762/49265354-9ffa3400-f4b6-11e8-8484-97d70ed8e428.png)

Hey, I've been trying to make the numberfilter appear inline but cant seem to figure out how its done. In the example above I want the >= and 0 boxes to appear on the same line. How would this be possible?

**Comment by AllenFang** [comment]
@vwen01 i think it should be inline, you can check the [online demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Number%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

Currently, we only allow you to custom the filter but not for re-arrange the position of filter's components.  Please give me some example that why your filter component is not inline.  I will suggest you to post your example on https://codesandbox.io so that I can help you, thanks
