### ISSUE TITLE
Can't edit keyField value

### ISSUE THREAD

**Issue by gmr** [react-bootstrap-table/react-bootstrap-table2#752]
Thanks for your project, other than this one issue, it's exactly what I was looking for.

I try and use natural keys instead of surrogate (numeric or otherwise) IDs for some tables where it makes sense. I'm running into an issue where the click to edit functionality when using cellEditFactory is not binding to the key field, preventing inline modification.

Ideally, if the keyField is marked as editable, it would be editable. I assume you are intentionally not binding the click event for it, but I could not find the exclusion in the code after a brief look. Am I missing a way to enable editing of a keyField value?

**Comment by AllenFang** [comment]
@gmr sorry for lately reply, I got serious disease since from last week.

The truth  is `keyField` is unique key  like data the RDB(Relational database system) which should not be changed to avoid some side effect. So last why I block it.

Please let me know more if you feel I can do more explain or improvement. thanks :)
