### ISSUE TITLE
Row selection broken in 1.4.2 when setting state in onSelect handler

### ISSUE THREAD

**Issue by peetw** [react-bootstrap-table/react-bootstrap-table2#769]
After updating `react-bootstrap-table-next` from `1.4.1` to `1.4.2`, row selection appears to be broken when providing an `onSelect` handler that modifies the parent component state. Specifically, if I have the following row selection props:

    const selectRow = {
        mode: "checkbox",
        clickToSelect: true,
        onSelect: (row, isSelect) => this.handleSelect(row, isSelect)
    };

And the following `handleSelect` method:

    private handleSelect(row, isSelect) {
        ...
        this.setState({ value: someValue });
    }

I am able to select/unselect a row without issue in 1.4.1, but after updating to 1.4.2 nothing happens when I click on the checkbox or row (the checkbox remains unchecked). However, if I remove the call to `this.setState(...)` in the `handleSelect` method, row selection/unselection works again. This behaviour also occurs for the `onSelectAll` handler.

Looking at the history, the only difference between 1.4.1 and 1.4.2 appears to be #699. Could this issue be related to the changes made in a7ae524?

**Comment by AllenFang** [comment]
@peetw yes, it did cause by `1.4.2`'s patch. That is because i want to give developer more selection management or control. However, if you really need to call `setState` in `selectRow.onSelect` or `selectRow.onSelectAll`, i will suggest you to manage the selection via `selectRow.selected`, just like [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Selection%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) example

Please let me know if you have any concern or questions, thanks 👍

**Comment by peetw** [comment]
Using `selectRow.selected` worked - thanks for the pointer!
