### ISSUE TITLE
Expand management

### ISSUE THREAD

**Issue by primakashi** [react-bootstrap-table/react-bootstrap-table2#785]
I have a problem when set default expanded row.
Expanded array option doesn't work.

This the option variable that I set.
 const expandRow = {
            renderer: this.expandRenderer,
            expanded: this.state.expanding,
            showExpandColumn: true,
            expandColumnRenderer: this.expandColumnRenderer,
 };

**Comment by rohit-sourcefuse** [comment]
HI, @primakashi I am also facing same issue default rows mention in the array for *expanded* property not working, i also check the spell and also pass something like that :
const expandRow = {
renderer: this.expandRenderer,
*expanded: [1.3],*
showExpandColumn: true,
expandColumnRenderer: this.expandColumnRenderer,
};
Can you explain, how your issue was fixed?

**Comment by primakashi** [comment]
In my case, I make a mistake. Expanded value must be value that used as key. 

For example

`const id = [ 'a','b','c']`
`<BootstrapTable
      keyField="id"
      data={nodeInterface}
      columns={columns}
      expandRow={expandRow}
/>
`

so expanded value must be

`expanded: [a,b]`

not number like 1,3

**Comment by rohit-sourcefuse** [comment]
Let me check this maybe this is also the case with me.
