### ISSUE TITLE
When I render a new set of data, the formatter doesn't apply to all of the fields

### ISSUE THREAD

**Issue by AshCorah** [react-bootstrap-table/react-bootstrap-table2#807]
I am rendering XYZ set of data that all go through the formatter: (cell, row) => option.

However, I have a selection option to get a different set of data. When I set the state of my components data to ABC data when the option is clicked, it's then passed to BootstrapTable but not every field/row go through the formatter option. Some do, some don't. 

![image](https://user-images.githubusercontent.com/26364927/53010568-8e358680-343e-11e9-9738-196dfe2ecc83.png)

Is there any way to force the tables data to go through the formatter every time?

**Comment by oitozero** [comment]
+1

**Comment by AllenFang** [comment]
@AshCorah would you please use [this](https://codesandbox.io/s/jlol04qrxv) example to create a simple and minimal example for me to reproduce this issue?  (be careful to the version of `react-bootstrap-table2` in above link)

This issue might be a bug or your formatter is not pure:

check [document](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function), there's something important

> Attention: Don't use any state data or any external data in formatter function, please pass them via formatExtraData. In addition, please make formatter function as pure function as possible as you can.

due to performance concerns, so that we hope developer can write a pure formatter so that we can decide if re-render a cell base on props only.

anyway, if ok, I want to check your XYZ and ABC dataset, thanks.

**Comment by AshCorah** [comment]
Don't worry, I have resolved my issue. I wasn't using a pure component. I've resolved the problem :)
Thanks for you help anyway!
