### ISSUE TITLE
Date Filter nor working right

### ISSUE THREAD

**Issue by mpnetto** [react-bootstrap-table/react-bootstrap-table2#808]
Hello,
I'm trying to implement the date Filter in an app, but aparently the equal comparator is not working as it should. In the example in the storyBrook (link below), I have to put one day after to get the date I want. For example: if I want to get 04 feb 2019, I have to put in the filter 05 feb 2019. Is there any way to correct this.

Thanks for the good work.

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Date%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by AllenFang** [comment]
<img width="844" alt="2019-02-20 11 52 01" src="https://user-images.githubusercontent.com/5351390/53104565-8b37b480-356a-11e9-8c30-6f1db6b304ca.png">

that is wired.... it work well for me

**Comment by AllenFang** [comment]
any more information?

**Comment by Glmnet1** [comment]
I had the same issue with the Date editor and the problem comes from parsing dates with getDate(), getMonth() and getFullYear() when the date input returns the selected date in UTC at midnight.

Switching to getUTCDate(), getUTCMonth() and getUTCFullYear() both in the Date editor docs and in the Date filter parser should fix this.

**Comment by AllenFang** [comment]
@Glmnet1   thanks, I will check your PR

**Comment by AllenFang** [comment]
Release https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/03/31/version-bump.html

Please let me know if the issue still remain, thanks
