### ISSUE TITLE
alwaysShowAllButtons on pagination does not show all buttons

### ISSUE THREAD

**Issue by nathan-fortier** [react-bootstrap-table/react-bootstrap-table2#838]
If you are on the first few pages the "First Page" button is missing when this flag is on. Similarly if you are on the last few pages the "Last Page" button is missing. It seems silly for the bar to jump around adding and removing buttons.

https://codesandbox.io/s/rpr0v789n?fontsize=14

**Comment by AllenFang** [comment]
@nathan-fortier i think it's correct behavior, please check the [doc](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/pagination-props.html#paginationalwaysshowallbtns-bool): 

> Default is false, which means react-bootstrap-table2 will hide the next or previous page button if unnecessary

in the implementation, we only show the next and prev button always instead of first and last page. However, I think this is my little mistake, because this props is "show all buttons", so I will do some enhancement to make sure all the buttons show up, thanks 👍

**Comment by nathan-fortier** [comment]
Yes per your doc it is correct however its not very robust and the prop name does suggest its going to show ALL buttons. In my case, I don't want the bar moving around a lot so I would prefer to show ALL buttons not just MOST of the buttons. Perhaps adding an option to pass an object (or array) of which buttons to always display so that you have the option to always show next and prev or always show first and last as well. Looking forward to what you decide.

alwaysShowAllButtons: true,
buttonsAlways: [prev,next]
or
buttonsAlways: [prev,next,first,last]

**Comment by AllenFang** [comment]
@nathan-fortier 

this issue is fixed, please at least to upgrade related package listed below to newest version:

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/03/26/version-bump.html
