### ISSUE TITLE
Pager not correct if data changes in grid

### ISSUE THREAD

**Issue by waynebrantley** [react-bootstrap-table/react-bootstrap-table2#878]
If something causes the data to completely change, the pager is not updated.
For example - an external search or just a button that swaps data out in the grid.

Complete example is here:
https://codesandbox.io/s/j7zppzyz19

**Comment by AllenFang** [comment]
@waynebrantley I think when you enable the remote pagination, the `page`, `sizePerPage` and `totalSize` will be necessary value for `pagination` props:

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/pagination-props.html#paginationpage-number

The reason is `react-bootstrap-table2` never know the size and the actual page of incoming data.

**Comment by waynebrantley** [comment]
@AllenFang Yes that works - however other than this 'one issue', you do NOT have to track the page number!   Was thinking you might be able to think of a solution to this....I think 'hooks' version of react would work - as we could potentially get a state setter for page of grid, etc.   But that may be the only way...

BTW, upgrade from stable 1.2 version all the way to 3.03 last week - looking good!!
