### ISSUE TITLE
Align pagination to the right

### ISSUE THREAD

**Issue by vealjoshua** [react-bootstrap-table/react-bootstrap-table2#888]
How to align pagination panel to the right? 

In some of the demos it is not clear which property is aligning the pagination.

**Comment by AllenFang** [comment]
@vealjoshua so far we didn't have this feature and it's minor feature to me. So PR is welcome.

In addition, you can still approach this by customizing  the pagination to rearrange the position of pagination component

**Comment by AllenFang** [comment]
Tips, use standalone component so that you can rearrange the position,

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-pagination.html

[demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Standalone%20Pagination%20List&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by AllenFang** [comment]
Please tag me if you still have any question, thanks!!

**Comment by haqim007** [comment]
@AllenFang Do you have example of using SizePerPageDropdownStandalone at the bottom align on the left and PaginationListStandalone align on the right?

**Comment by yeetyeetROG** [comment]
@vealJoshua You can set in `style.css` something like this and it will float right
`.pagination .react-bootstrap-table-page-btns-ul {
    float: right!important
}`

**Comment by sachitha-94** [comment]
import following CSS
`import 'react-bootstrap-table2-paginator/dist/react-bootstrap-table2-paginator.min.css';`
