### ISSUE TITLE
Remote set a Cell editingColIdx and editingRowIdx

### ISSUE THREAD

**Issue by gabrieldonadel** [react-bootstrap-table/react-bootstrap-table2#978]
Is there a way that I can remotely set editingColIdx and editingRowIdx so that when I add a new row a cell of it already came in the editor mode?

**Comment by AllenFang** [comment]
@gabrieldonadel hmm..  i think it's not so easy to implement lol .  in deprecated `react-bootstrap-table`, we had similar case that is due to we natively support "row adding" functionality.  but so far we don't have in this package.  In my perspective, this requirement is a big stuff for me, I mean we probably need to implement row adding, in addition, this feature is not make sense to be a part of cell editing.

**Comment by AllenFang** [comment]
Let's close it due to i will not implement it. but as I mention, this should be the part of row adding.
